"""add_cascade_for_user_fk

Revision ID: 2ae4b4dd70ee
Revises: 0bdf41e28b93
Create Date: 2025-04-23 02:41:44.051754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae4b4dd70ee'
down_revision: Union[str, None] = '0bdf41e28b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('habit_user_id_fkey', 'habit', type_='foreignkey')
    op.create_foreign_key(None, 'habit', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habit', type_='foreignkey')
    op.create_foreign_key('habit_user_id_fkey', 'habit', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
