"""Add_unique_contraint_for_progress

Revision ID: b35d1883140e
Revises: 0a7fe2652273
Create Date: 2025-04-16 23:58:15.671145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35d1883140e'
down_revision: Union[str, None] = '0a7fe2652273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_created_date', 'progress', ['habit_id', 'created_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_created_date', 'progress', type_='unique')
    # ### end Alembic commands ###
