"""add_cascade_deletion

Revision ID: c0a52a41a0ce
Revises: 50a1c1c8a04d
Create Date: 2025-04-20 03:16:44.699691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a52a41a0ce'
down_revision: Union[str, None] = '50a1c1c8a04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('progress_habit_id_fkey', 'progress', type_='foreignkey')
    op.create_foreign_key(None, 'progress', 'habit', ['habit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'progress', type_='foreignkey')
    op.create_foreign_key('progress_habit_id_fkey', 'progress', 'habit', ['habit_id'], ['id'])
    # ### end Alembic commands ###
