"""add_cascade_for_progress_fk

Revision ID: d063b92306e3
Revises: 2ae4b4dd70ee
Create Date: 2025-04-23 02:42:50.090766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd063b92306e3'
down_revision: Union[str, None] = '2ae4b4dd70ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('progress_user_id_fkey', 'progress', type_='foreignkey')
    op.create_foreign_key(None, 'progress', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'progress', type_='foreignkey')
    op.create_foreign_key('progress_user_id_fkey', 'progress', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
