"""Add_goal_progress_field

Revision ID: fb54ce9cd79f
Revises: b35d1883140e
Create Date: 2025-04-17 02:59:17.104290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb54ce9cd79f'
down_revision: Union[str, None] = 'b35d1883140e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress', sa.Column('goal', sa.Integer(), nullable=False, server_default="100"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progress', 'goal')
    # ### end Alembic commands ###
